openapi: 3.1.0
info:
  title: Allente API for customer information
  version: '1.0'
  description: Provides Customer information
  contact:
    name: Allente
servers:
  - url: 'https://stoplight.io/mocks/sci-code/diggit:master/10924359'
    description: Mock server
paths:
  '/customer/{customerId}':
    get:
      operationId: getCustomerInfo
      summary: Get customer information including product ids.
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 200 response
          content:
            application/json; charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Customer'
              examples:
                example-ok:
                  value:
                    id: 2686
                    name: Michael Simmons
                    emailAddress: simmons@diggit.no
                    StreamingProviderProductIds:
                      - 5842
                      - 4539
                    streamingProviderIds:
                      - 37
                      - 29
      description: Fetch customer data
    put:
      operationId: updateCustomerInfo
      summary: Update customer information including product ids.
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Updated!
          content:
            application/json; charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Customer'
      description: Update Customer data
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerUpdate'
        description: ''
    parameters:
      - schema:
          type: string
        name: customerId
        in: path
        required: true
components:
  schemas:
    Customer:
      type: object
      examples:
        - id: 78
          name: Michael Simmons
          emailAddress: simmons@diggit.no
          StreamingProviderProductIds:
            - 3719
            - 1511
          streamingProviderIds:
            - 37
            - 29
      properties:
        id:
          type: integer
          format: int32
          minimum: 1
          maximum: 10000
        name:
          type: string
          example: Michael
          minLength: 2
          maxLength: 30
        emailAddress:
          type: string
          format: email
          example: simmons@diggit.no
          minLength: 3
          maxLength: 40
        StreamingProviderProductIds:
          type: array
          uniqueItems: true
          minItems: 1
          maxItems: 30
          items:
            type: integer
            format: int32
            minimum: 1000
            maximum: 10000
        streamingProviderIds:
          type: array
          minItems: 1
          uniqueItems: true
          maxItems: 15
          items:
            type: integer
            format: int32
            minimum: 1
            example: 7
            maximum: 99
    CustomerUpdate:
      title: CustomerUpdate
      type: object
      properties:
        StreamingProviderProductIds:
          type: array
          uniqueItems: true
          items:
            type: integer
            minimum: 1000
            maximum: 10000
        streamingProviderIds:
          type: array
          uniqueItems: true
          items:
            type: integer
            minimum: 1
            maximum: 99
  securitySchemes: {}
