openapi: 3.1.0
info:
  title: Allente API for customer information
  version: '1.0'
  description: Provides Customer information
  contact:
    name: Allente
servers:
  - url: 'https://stoplight.io/mocks/sci-code/diggit:master/10924359'
    description: Mock server
paths:
  '/customer/{customerId}':
    get:
      operationId: getCustomerInfo
      summary: Get customer information including product ids.
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 200 response
          content:
            application/json; charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Customer'
              examples:
                one-example:
                  value:
                    name: Michael Simmons
                    emailAddress: simmons@diggit.no
                    activeServices:
                      - Coyote TV
                      - Paramount
                another-example:
                  value:
                    name: James Franco
                    emailAddress: franco@diggit.no
                    activeServices:
                      - HBO
                      - Warner
      description: Fetch customer object
    put:
      operationId: updateCustomerInfo
      summary: Update customer information including product ids.
      parameters:
        - name: customerId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Updated!
          content:
            application/json; charset=UTF-8:
              schema:
                type: string
              examples:
                example-1:
                  value: Updated the user!
      description: Update Customer data
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerUpdate'
            examples: {}
        description: ''
    parameters:
      - schema:
          type: string
        name: customerId
        in: path
        required: true
components:
  schemas:
    Customer:
      type: object
      examples: []
      properties:
        name:
          type: string
          example: Michael
          minLength: 2
          maxLength: 30
        emailAddress:
          type: string
          format: email
          example: simmons@diggit.no
          minLength: 3
          maxLength: 40
        activeServices:
          type: array
          uniqueItems: true
          minItems: 0
          maxItems: 10
          items:
            type: string
            minLength: 2
            maxLength: 10
    CustomerUpdate:
      title: CustomerUpdate
      type: object
      properties:
        activeServices:
          type: array
          uniqueItems: true
          items:
            type: string
            minLength: 2
            maxLength: 10
      examples: []
  securitySchemes: {}
