openapi: 3.0.1
info:
  title: Acme API for subscriber management
  version: '1.0'
  description: Helps to subscribe customer to any Streaming Service
  contact:
    name: Allente
servers:
  - url: 'https://stoplight.io/mocks/sci-code/diggit:master/10924619'
    description: Mock
paths:
  /subscriber:
    post:
      operationId: createSubscriber
      summary: Create subscriber
      requestBody:
        content:
          application/json; charset=UTF-8:
            schema:
              $ref: '#/components/schemas/Subscriber'
        required: true
        description: ''
      responses:
        '200':
          description: Subscriber successfully created.
          content:
            application/json; charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Response'
        '400':
          description: The server cannot or will not process the request due to something that is perceived to be a client error. See details in response body.
          content:
            application/json; charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Response'
        '500':
          description: Internal server error. Please try again later.
          content:
            application/json; charset=UTF-8:
              schema:
                $ref: '#/components/schemas/Response'
      description: ''
components:
  schemas:
    Subscriber:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        products:
          type: array
          items:
            type: string
      required:
        - name
        - email
        - products
    Response:
      type: object
      properties:
        httpCode:
          type: string
        reasonCode:
          type: string
          enum:
            - OK
            - SUBSCRIBER_ALREADY_EXISTS
            - INVALID_REQUEST
            - INTERNAL_SERVER_ERROR
        message:
          type: string
      x-examples:
        example:
          value:
            httpCode: '200'
            reasonCode: OK
            message: Everything is fine
