openapi: 3.1.0
info:
  title: Carousel
  version: '1.0'
  summary: API for carousel
  contact:
    name: Allente
  description: Carouel API for getting movie recommendations
servers:
  - url: 'http://localhost:3000'
paths:
  /recommendations:
    parameters: []
    post:
      summary: Get recommendations
      operationId: post-recommendations
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Movie'
              examples:
                example:
                  value:
                    - id: 8127453
                      details:
                        director:
                          - Ben Winston
                        cast:
                          - Lisa Kudrow
                          - Jennifer Aniston
                          - David Schwimmer
                        year: 2021
                        length: 103
                        channelId: hbo
                      publishDate: '2021-05-27T09:01:00+0200'
                      contentType: video
                      title: 'Friends: The Reunion'
                      description:
                        short: An unscripted Friends reunion special.
                        long: 'Our favorite friends are back on the set where it all started. Jennifer Aniston, Courteney Cox, Lisa Kudrow, Matt LeBlanc, Matthew Perry, David Schwimmer and other invited guests are reunited for an impromptu tribute to the beloved show.'
                      images:
                        background:
                          url: 'https://cd-static2.telenorcdn.net/zuul/dis-api//4o2-jhb2sULGEvnHxorjy6iepSA=/60x86/smart/cdn-cd-production.cloud.xstream.dk/thumbnails/2021/05/27/1622108701017768900.jpg'
                      tags:
                        - hd
                      genres:
                        - Documentary
                        - Comedy
        '404':
          description: No movies Found
      description: Get recommendations for movies to watch based on user preferences
      requestBody:
        content:
          application/json:
            schema:
              type: array
              uniqueItems: true
              items:
                type: string
                enum:
                  - Documentary
                  - Comedy
                  - Drama
                  - Thriller
                  - Action
                  - Fantasy
                  - Horror
                minLength: 1
            examples:
              example:
                value:
                  - Documentary
                  - Drama
components:
  schemas:
    Movie:
      title: User
      type: object
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given movie.
        details:
          type: object
          required:
            - director
            - cast
            - year
            - length
            - channelId
          description: Details on given movie
          properties:
            director:
              type: array
              items:
                type: string
            cast:
              type: array
              items:
                type: string
            year:
              type: integer
            length:
              type: integer
            channelId:
              type: string
        publishDate:
          type: string
          description: When it was published on Streaming Provider
        contentType:
          type: string
          description: ''
        title:
          type: string
        description:
          description: ''
          required:
            - short
            - long
          type: object
          properties:
            short:
              type: string
              description: For the carousel card
            long:
              type: string
              description: For the movie modal
        images:
          type: object
          description: The date that the user was created.
          required:
            - background
          properties:
            background:
              type: object
              required:
                - url
              properties:
                url:
                  type: string
        tags:
          type: array
          description: 'Extra tags for filtering ("hd", "hot" etc.)'
          items:
            type: string
        genres:
          type: array
          uniqueItems: true
          minItems: 1
          items:
            type: string
            enum:
              - Documentary
              - Comedy
              - Drama
              - Thriller
              - Horror
              - Action
              - Fantasy
      required:
        - id
        - details
        - publishDate
        - contentType
        - title
        - description
        - images
        - genres
